### ISSUE TITLE
Error: E-mail is not yet verified

### ISSUE THREAD

**Issue by Per0x** [psono/psono-server#1]
Hello,

I installed psono-postgres, psono-server, and psono-client on docker, 
everything seems to be fine, and when I send the test mail, I receive the mail "If you read this, then everything is correctly configured. "
But when I try to register a new user in the web client, no mail is sent, so I'm stuck with the message "Error: E-mail is not yet verified."

**Comment by chickahoona** [comment]
Hi Per0x. Hmm thats wierd. Did you check your spam folder?

**Comment by Per0x** [comment]
Yes I checked spams and it's not a problem of spam, the mail is not sent at all, I also checked in the logs of my smtp server and there's nothing there except when I send with the test command `./psono/manage.py sendtestmail something@something.com`

**Comment by chickahoona** [comment]
Hmm ... are you running the server "bare metal" or with docker?

Is there something inside of the logs?

**Comment by Per0x** [comment]
I'm running the containers with docker on my private server.

The logs when I create a new user:

`[pid: 20|app: 0|req: 57/183] 172.17.0.1 () {46 vars in 854 bytes} [Thu Sep 13 18:56:52 2018] OPTIONS /authentication/register/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 8 headers in 502 bytes (1 switches on core 0)`

`[pid: 20|app: 0|req: 58/185] 172.17.0.1 () {46 vars in 855 bytes} [Thu Sep 13 18:57:52 2018] POST /authentication/register/ => generated 76 bytes in 1123 msecs (HTTP/1.1 400) 7 headers in 261 bytes (1 switches on core 0)`

When I login with the new user (not validated by email):

`[pid: 22|app: 0|req: 27/186] 172.17.0.1 () {46 vars in 828 bytes} [Thu Sep 13 18:58:31 2018] OPTIONS /info/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 8 headers in 502 bytes (1 switches on core 0)`

`[pid: 26|app: 0|req: 54/187] 172.17.0.1 () {48 vars in 844 bytes} [Thu Sep 13 18:58:31 2018] GET /info/ => generated 697 bytes in 4 msecs (HTTP/1.1 200) 7 headers in 252 bytes (1 switches on core 0)`

`[pid: 18|app: 0|req: 5/188] 172.17.0.1 () {46 vars in 835 bytes} [Thu Sep 13 18:58:32 2018] OPTIONS /authentication/login/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 8 headers in 502 bytes (1 switches on core 0)`

`[pid: 18|app: 0|req: 6/189] 172.17.0.1 () {46 vars in 836 bytes} [Thu Sep 13 18:58:32 2018] POST /authentication/login/ => generated 52 bytes in 592 msecs (HTTP/1.1 400) 7 headers in 261 bytes (1 switches on core 0)`

`[pid: 25|app: 0|req: 17/190] 172.17.0.1 () {46 vars in 855 bytes} [Thu Sep 13 18:56:52 2018] POST /authentication/register/ => generated 27 bytes in 129153 msecs (HTTP/1.1 500) 6 headers in 236 bytes (1 switches on core 0)`

`[pid: 26|app: 0|req: 55/191] 127.0.0.1 () {24 vars in 278 bytes} [Thu Sep 13 18:59:26 2018] GET /healthcheck/ => generated 84 bytes in 180 msecs (HTTP/1.1 200) 5 headers in 149 bytes (1 switches on core 0)`

**Comment by chickahoona** [comment]
Hm, looks like your registration is failing for some reason:

[pid: 20|app: 0|req: 58/185] 172.17.0.1 () {46 vars in 855 bytes} [Thu Sep 13 18:57:52 2018] POST /authentication/register/ => generated 76 bytes in 1123 msecs (HTTP/1.1 400) 7 headers in 261 bytes (1 switches on core 0)

(Error Code 400)

You can enable DEBUG mode in your settings.yaml (restart the docker image afterwards) and then check the POST request in your javascript developer console. It should contain some valuable output for you.

**Comment by Per0x** [comment]
Ok, I will enable DEBUG and redo the manipulation. But I think this error may be due to the fact that I clicked a second time on "Register" with a result message like "email address already used"

**Comment by chickahoona** [comment]
Maybe you did a last final change to the settings.yaml and didnt restart your psono server afterwards.

**Comment by chickahoona** [comment]
Dont forget to disable the DEBUG mode again as it may expose secrets.

**Comment by Per0x** [comment]
> Maybe you did a last final change to the settings.yaml and didnt restart your psono server afterwards.

I had already restarted three times. The main thing is that now it works. And thank you for the reminder to disable the DEBUG mode.
