### ISSUE TITLE
Sorting of entries

### ISSUE THREAD

**Issue by bobhydrm** [psono/psono-server#5]
Hi, psono seems to be excellent app, but we have two ideas:

1) Entries sorting .... Viewing of tree structure should be better is user can sort entries (alfabetically) ... folders or passwords entries
2) Configurable automatic logout ... from the administrators view, I'd like to set timeout for automaticall logout (now its 24h for untrusted, 30d for trusted devices). I think this is good idea to improve security.

**Comment by chickahoona** [comment]
Both are already tracked here:
https://gitlab.com/psono/psono-client/issues/30
https://gitlab.com/psono/psono-client/issues/18

But thank you for your interest :)
