### ISSUE TITLE
G-Auth vanishes after PW reset

### ISSUE THREAD

**Issue by istoOi** [psono/psono-server#6]
Resetting the password removes the Google Auth entry in the database. Yet G-Auth is still activated for the account.
This results in a "No Google Authenticator found." error message when i try to enter my G-Auth code at login.

**Comment by chickahoona** [comment]
Thank you very much! I created an issue here https://gitlab.com/psono/psono-server/issues/74
I really appreciate your help! Ill soon release a fix for it. To fix your user you have to check the restapi_user table, find your user and set google_authenticator_enabled to false. I'm sorry for the trouble.

**Comment by istoOi** [comment]
You're welcome :)
wasn't a big issue, since it is still in testing phase. And i got Adminer to resolve it quickly.

**Comment by chickahoona** [comment]
I'm glad that you could resolve it yourself. Speaks loudly about your skills ;)
There is now a new release, that has the fix for this problem to prevent it for others. Thank you very much for reporting this issue!
