### ISSUE TITLE
Can't Access Info page after installing Psono Server EE in docker

### ISSUE THREAD

**Issue by birduser** [psono/psono-server#7]
Hey there,
after installing the Server on my Debian 10 based system I'm having issues to connect over IP:Port(10100) through my browser. I'm not very experienced with Docker based systems so I might be overseeing something so some help would be great. I've installed it following your documentation with postgres and docker installed. I'll happily provide any information needed to help solve my issue.

Edit: Some more infos:

System: Debian 10
Docker: 2 Docker Containers running & Healthy (Portainer and psono-server-enterprise)
Local and LAN internal Telnet to port 10100 results in errors (no connect)
Database connection works fine

I've attached my settings.yaml for review, maybe I've missed something there.
[settings.yaml.txt](https://github.com/psono/psono-server/files/3634787/settings.yaml.txt)

Best regards
bird

**Comment by chickahoona** [comment]
Hi birduser, could you execute "docker ps" for me?

**Comment by birduser** [comment]
Sure, docker ps output:

448baf8310c4        psono/psono-server-enterprise:latest   "/bin/sh /root/confi…"   29 hours ago        Up 6 seconds (health: starting)   0.0.0.0:10100->80/tcp    psono-server-enterprise

b833d7de4b54        portainer                              "/portainer"             2 days ago          Up 6 seconds                      0.0.0.0:9000->9000/tcp   portainer

**Comment by chickahoona** [comment]
Your docker container keeps restarting, as it does not reach a healthy state. You could check the logs. (command: docker logs...).
A second possibility would be to start the server "interactively" with:

1. `docker run -it --name psono-server-enterprise --sysctl net.core.somaxconn=65535 -v /path/to/settings.yaml:/root/.psono_server/settings.yaml -p 10100:80 psono/psono-server-enterprise:latest /bin/sh` then you are "inside" of the docker container, afterwards the following command
2. `python3 psono/manage.py runserver 0.0.0.0:80`

I also checked your settings.yaml. It is odd that your lines start with leading whitespaces. Leading whitespaces in yaml are considered to be comments and are ignored, which could be the source of your problem.

**Comment by birduser** [comment]
Sorry I made two mistakes which probably led you to wrong conclusions.
1. I just started the VM so the containers where still booting, my bad. This is the actuall running status:
448baf8310c4        psono/psono-server-enterprise:latest   "/bin/sh /root/confi…"   29 hours ago        Up 12 minutes (healthy)   0.0.0.0:10100->80/tcp    psono-server-enterprise
b833d7de4b54        portainer                              "/portainer"             2 days ago          Up 12 minutes             0.0.0.0:9000->9000/tcp   portainer

2. The whitespaces are only in the txt not in the actual settings.yaml (I've double checked) as a result of copy/pasting 

I see I need to work on my reporting skills... Did you see anything else odd in the settings.yaml that might cause my issues?

**Comment by chickahoona** [comment]
hmm and if you open thje following URL in your browser http://xxx.xxx.xxx.xxx:10100/info/ (replace xxx.xxx.xxx.xxx with the IP of your server) does not show anything... strange.

Do you maybe have ipv6 enabled or a local firewall?

**Comment by birduser** [comment]
I have deleted all rules on the local iptables and also disabled ipv6. Unfortunately this didn't solve my Issue. I've also thought that there might be an Issue with portainer as this also runs a webinterface. I will check this over the weekend and will get back to you once I have a result. Thanks for your help so far!

**Comment by chickahoona** [comment]
I am sorry that I could not help you better :/

You could run the webclient and check if that one comes up. The webclient is a very simple docker container, only running and an nginx with static files, so if that one does not come up then there is something off with the docker host. If you get something there, then we have to investigate why the server would not start.

**Comment by birduser** [comment]
No worries you've been helpfull in the process of finden the error. After changing the port 10100 to 80 and for another test to 991 I got it to work as expected. Is there a specific reason to use 10100 or am I free to use any port to my liking?

**Comment by chickahoona** [comment]
Amazing that you could make it work. The port in general does not matter and you can change it as you like. The only "advantage" that you get with the "default ports" is the ability copy paste code snippets from the docu more easily, without any additional brainpower to map your network port to the one in the docu ;)

**Comment by chickahoona** [comment]
I am closing this issue if it works now.

**Comment by birduser** [comment]
Alright thanks for your help!
